strg="Linux works powerfull"
# print(strg)
# print("Length of strg is : ",len(strg))
# print("First 8 character of stg: ",strg[0:8])   #including 0 but excluding 8
# print("First 8 character with gap of 1 letter", strg[0:8:2])
# print("All character with gap of 1 letter", strg[0::2])
# print("All character of strg :",strg[::])
# print("String in reverse order:",strg[::-1])
# print ("String with negative sign:",strg[0:-4])
# print("count of character u",strg.count("u"))
# print("Lowercase",strg.lower())
# print("uppercase",strg.upper())
# print("find index of letter p",strg.find("p"))
# print("Remove trailing character:",strg.rstrip("ll"))
# print("Replace Linux string with Unix string :",strg.replace("Linux","Unix"))
# print("Split the string with space filter and convert to List: ",strg.split(" "))
course = "i WANT to leaRN dEVoPS."
# print(course)
# print("Capatalize first character and other character in lower case : ",course.capitalize())
# print("Move to centre:",strg.center(40))
# print(strg.isalnum())
# print(strg.isalpha())
# print("check if ending with full:",strg.endswith("full"))
# print("find index value of first occurence of the word power:",strg.find("power"))
# print("index value same as find:",strg.index("power"))
print ("Replace Linux with Unix:", strg.replace("Linux","Unix"))
unix_course = strg.replace("Linux","Unix")
print("Key Benefit of Unix :",unix_course)